#!/bin/sh


BASEDIR=$(pwd)


checkout()
{

	echo "Processing source/$1..."

	cd $BASEDIR/$1


	git fetch
	git checkout basis
	git pull

}


checkout platform-freebsd
checkout platform-posix
checkout storage-freebsd
checkout third-freebsd
checkout tool-freebsd


